[package]
name = "nautilus-custom-terminal"
version = "0.1.0"
authors = ["Edwin Svensson <nct@olback.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nautilus-extension = "0.5"
dirs = "2.0"
